import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { radius, spacing, typography } from '../../../theme/layout';
import type { ThemeColors } from '../../../theme/themes';

export const createChatThemeStyles = (theme: ThemeColors) => {
  const ownBubbleBg = theme.isDark
    ? theme.id === 'amoled-void'
      ? '#163d37'
      : '#24594f'
    : '#d8fdd2';
  const ownBubbleText = theme.isDark ? '#f5faf7' : '#173026';
  const otherBubbleBg = theme.isDark
    ? theme.id === 'amoled-void'
      ? '#0c1112'
      : '#1d2729'
    : '#ffffff';
  const otherBubbleText = theme.isDark ? '#f4f7fb' : '#172033';
  const otherBubbleBorder = theme.isDark
    ? 'rgba(218, 228, 220, 0.1)'
    : 'rgba(69, 80, 64, 0.08)';

  return StyleSheet.create({
    chatBackground: {
      backgroundColor: theme.background,
    },
    card: {
      backgroundColor: theme.card,
      borderColor: theme.border,
    },
    cardMuted: {
      backgroundColor: theme.cardMuted,
      borderColor: theme.border,
    },
    surfaceBar: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderTopColor: theme.border,
    },
    composerDock: {
      backgroundColor: 'transparent',
      borderTopColor: 'transparent',
      zIndex: 2,
    },
    composerSurface: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOpacity: theme.isDark ? 0.1 : 0.14,
      elevation: theme.isDark ? 2 : 5,
    },
    surfaceMutedBar: {
      backgroundColor: theme.surfaceMuted,
      borderTopColor: theme.border,
    },
    surfaceMuted: {
      backgroundColor: theme.surfaceMuted,
    },
    input: {
      backgroundColor: theme.input,
      borderColor: theme.border,
      color: theme.text,
    },
    text: {
      color: theme.text,
    },
    messageText: {
      color: otherBubbleText,
    },
    messageBodyText: {
      fontSize: 16,
      lineHeight: 21,
    },
    outgoingMessageText: {
      color: ownBubbleText,
    },
    composerInputText: {
      fontSize: 16,
      lineHeight: 21,
    },
    outgoingAccentText: {
      color: ownBubbleText,
      opacity: 0.9,
    },
    outgoingMutedText: {
      color: ownBubbleText,
      opacity: 0.78,
    },
    outgoingSoftText: {
      color: ownBubbleText,
      opacity: 0.68,
    },
    outgoingLink: {
      color: ownBubbleText,
      textDecorationLine: 'underline',
    },
    mutedText: {
      color: theme.muted,
    },
    softText: {
      color: theme.soft,
    },
    accentText: {
      color: theme.accent,
    },
    dangerText: {
      color: theme.danger,
    },
    dangerSoft: {
      backgroundColor: theme.dangerSoft,
    },
    accentBg: {
      backgroundColor: theme.accent,
    },
    accentLeftBorder: {
      borderLeftColor: theme.accent,
    },
    incomingBubble: {
      backgroundColor: otherBubbleBg,
      borderColor: otherBubbleBorder,
    },
    outgoingBubble: {
      backgroundColor: ownBubbleBg,
      borderColor: theme.isDark
        ? 'rgba(83, 190, 155, 0.24)'
        : 'rgba(83, 154, 91, 0.2)',
      borderWidth: StyleSheet.hairlineWidth,
    },
    replyPreview: {
      backgroundColor: theme.surfaceMuted,
      borderLeftColor: theme.accent,
    },
    voiceAttachment: {
      backgroundColor: theme.surfaceMuted,
    },
    videoNoteOrbit: {
      borderColor: theme.accent,
      backgroundColor: theme.surfaceMuted,
      shadowColor: theme.accent,
    },
    videoNoteOrbitActive: {
      borderColor: theme.accentStrong,
    },
    videoNoteGlassButton: {
      borderColor: theme.isDark
        ? 'rgba(255, 255, 255, 0.34)'
        : 'rgba(255, 255, 255, 0.72)',
    },
    videoNotePill: {
      backgroundColor: theme.isDark
        ? 'rgba(2, 6, 23, 0.68)'
        : 'rgba(15, 23, 42, 0.56)',
    },
    videoNotePillProgress: {
      backgroundColor: theme.accentSoft,
    },
    sheetBackdrop: {
      backgroundColor: theme.overlay,
    },
    sheet: {
      backgroundColor: theme.surface,
    },
    sheetHandle: {
      backgroundColor: theme.border,
    },
    sheetActionIcon: {
      backgroundColor: theme.surfaceMuted,
      color: theme.muted,
    },
    forwardRecipient: {
      backgroundColor: theme.surfaceMuted,
      borderColor: theme.border,
    },
    forwardRecipientSelected: {
      borderColor: theme.accent,
      backgroundColor: theme.selected,
    },
    forwardCheck: {
      backgroundColor: theme.surface,
      color: theme.muted,
    },
    forwardCheckSelected: {
      backgroundColor: theme.accent,
      color: theme.white,
    },
    scrollToLatestButton: {
      backgroundColor: theme.surface,
      borderColor: theme.border,
      shadowColor: theme.shadow,
    },
    scrollToLatestButtonNew: {
      backgroundColor: theme.accent,
      borderColor: theme.accent,
    },
  });
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 0,
    position: 'relative',
    overflow: 'hidden',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  loadingOlder: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  chatHeaderTitleButton: {
    flexShrink: 1,
    maxWidth: 220,
    minWidth: 0,
    minHeight: 32,
    justifyContent: 'center',
    borderRadius: radius.pill,
    paddingHorizontal: 6,
  },
  chatHeaderTitleText: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
  },
  messageListContainer: {
    flex: 1,
    zIndex: 1,
    backgroundColor: 'transparent',
  },
  transparentBackground: {
    backgroundColor: 'transparent',
  },
  callActions: {
    display: 'none',
  },
  messageList: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 8,
    flexGrow: 1,
    backgroundColor: 'transparent',
  },
  emptyMessageList: {
    justifyContent: 'center',
  },
  scrollToLatestButton: {
    position: 'absolute',
    right: 14,
    bottom: 14,
    minWidth: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOpacity: colors.isDark ? 0.16 : 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: colors.isDark ? 2 : 6,
    zIndex: 6,
  },
  scrollToLatestButtonNew: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  scrollToLatestText: {
    color: colors.white,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
  },
  bubbleRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  bubbleRowSpacing: {
    marginBottom: 4,
  },
  bubbleRowGroupedSpacing: {
    marginBottom: 2,
  },
  bubbleRowOutgoing: {
    justifyContent: 'flex-end',
  },
  bubble: {
    maxWidth: '78%',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
    gap: spacing.xs,
    position: 'relative',
    shadowColor: colors.shadow,
    shadowOpacity: 0.02,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 0,
  },
  bubbleWithFloatingFooter: {
    paddingBottom: 22,
  },
  incoming: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderBottomLeftRadius: 6,
  },
  outgoing: {
    backgroundColor: colors.accent,
    borderBottomRightRadius: 6,
  },
  messageText: {
    fontSize: 16,
    lineHeight: 21,
    color: colors.text,
  },
  messageInlineFooter: {
    fontSize: 12,
    lineHeight: 14,
  },
  messageFooter: {
    position: 'absolute',
    right: 8,
    bottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  messageFooterMeasure: {
    opacity: 0,
  },
  messageFooterTime: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '500',
  },
  messageFooterChecks: {
    marginLeft: 1,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    letterSpacing: -1,
  },
  outgoingText: {
    color: colors.white,
  },
  messageLink: {
    color: colors.accent,
    textDecorationLine: 'underline',
  },
  outgoingLink: {
    color: colors.white,
    textDecorationLine: 'underline',
  },
  forwardedLabel: {
    ...typography.tiny,
    color: colors.accent,
    fontWeight: '800',
  },
  forwardedLabelOutgoing: {
    color: colors.white,
  },
  replyPreview: {
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  replyPreviewOutgoing: {
    borderLeftColor: colors.white,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  replyPreviewAuthor: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  replyPreviewAuthorOutgoing: {
    color: colors.white,
  },
  replyPreviewText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  replyPreviewTextOutgoing: {
    color: 'rgba(248, 250, 252, 0.82)',
  },
  messageDate: {
    ...typography.tiny,
    color: colors.soft,
    alignSelf: 'flex-end',
    marginTop: 1,
  },
  outgoingDate: {
    color: colors.muted,
  },
  outgoingStatus: {
    color: colors.accent,
    ...typography.tiny,
    alignSelf: 'flex-end',
  },
  messageImage: {
    width: 210,
    height: 150,
    borderRadius: radius.lg,
    backgroundColor: colors.surfaceMuted,
  },
  genericVideoAttachment: {
    width: 230,
    borderRadius: radius.lg,
    overflow: 'hidden',
    backgroundColor: colors.surfaceMuted,
  },
  genericVideo: {
    width: 230,
    height: 150,
    backgroundColor: '#000',
  },
  genericVideoPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  genericVideoPlay: {
    position: 'absolute',
    left: 95,
    top: 55,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.58)',
  },
  genericVideoPlayText: {
    color: colors.white,
    fontSize: 18,
    marginLeft: 2,
  },
  genericAttachmentMeta: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 12,
  },
  linkPreviewCard: {
    marginTop: spacing.sm,
    width: 230,
    borderRadius: radius.lg,
    overflow: 'hidden',
    padding: spacing.sm,
    gap: spacing.xs,
  },
  linkPreviewThumb: {
    width: '100%',
    height: 112,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceMuted,
  },
  linkPreviewThumbPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkPreviewProvider: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  linkPreviewTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  linkPreviewUrl: {
    fontSize: 12,
  },
  linkPreviewStatus: {
    fontSize: 12,
  },
  linkPreviewFailed: {
    color: colors.danger,
    fontSize: 12,
  },
  linkPreviewActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  linkPreviewButton: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.accent,
  },
  linkPreviewButtonDisabled: {
    opacity: 0.6,
  },
  linkPreviewButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  linkPreviewSecondaryButton: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
  },
  linkPreviewSecondaryText: {
    fontSize: 12,
    fontWeight: '700',
  },
  linkPreviewSource: {
    marginTop: spacing.xs,
    fontSize: 12,
  },
  genericFileAttachment: {
    minWidth: 220,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  genericFileIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
  },
  genericFileIconText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '800',
  },
  attachmentDecryptError: {
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.dangerSoft,
  },
  attachmentDecryptErrorOutgoing: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  attachmentDecryptErrorText: {
    color: colors.danger,
    fontSize: 14,
    fontStyle: 'italic',
  },
  attachmentDecryptErrorTextOutgoing: {
    color: colors.white,
  },
  voiceAttachment: {
    minWidth: 220,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surfaceMuted,
  },
  voiceAttachmentOutgoing: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  voicePlayButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
  },
  voicePlayButtonActive: {
    backgroundColor: colors.accentStrong,
  },
  voicePlayText: {
    color: colors.white,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
  },
  voiceInfo: {
    flex: 1,
    minWidth: 0,
  },
  voiceTitle: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  voiceTitleOutgoing: {
    color: colors.white,
  },
  voiceDuration: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  voiceDurationOutgoing: {
    color: 'rgba(248, 250, 252, 0.78)',
  },
  videoNoteAttachment: {
    width: 116,
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    paddingVertical: 2,
    backgroundColor: colors.surfaceMuted,
  },
  videoNoteAttachmentOutgoing: {
    alignSelf: 'flex-end',
  },
  videoNoteOrbit: {
    width: 104,
    height: 104,
    borderRadius: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.accent,
    backgroundColor: colors.surfaceMuted,
    overflow: 'hidden',
    shadowColor: colors.accent,
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  videoNoteOrbitActive: {
    borderColor: colors.accentStrong,
    shadowOpacity: 0.36,
    shadowRadius: 18,
  },
  videoNoteVideo: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.surfaceMuted,
  },
  videoNotePlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
  },
  videoNoteGlassButton: {
    position: 'absolute',
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.32)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.48)',
  },
  videoNoteIcon: {
    color: colors.white,
    fontSize: 16,
    lineHeight: 19,
    fontWeight: '900',
    textAlign: 'center',
    textShadowColor: 'rgba(2, 6, 23, 0.42)',
    textShadowRadius: 6,
  },
  videoNotePill: {
    minWidth: 48,
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: 'rgba(2, 6, 23, 0.58)',
  },
  videoNotePillProgress: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
  },
  videoNoteText: {
    minWidth: 42,
    color: colors.white,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 2,
    textAlign: 'center',
  },
  videoNoteTextOutgoing: {
    color: colors.white,
  },
  previewStrip: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: 22,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOpacity: colors.isDark ? 0.08 : 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: colors.isDark ? 1 : 3,
  },
  previewStripContent: {
    gap: spacing.sm,
    paddingRight: spacing.xs,
  },
  previewItem: {
    width: 72,
    height: 72,
  },
  previewImage: {
    width: 72,
    height: 72,
    borderRadius: 16,
    backgroundColor: colors.surfaceMuted,
  },
  previewVideoCard: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    minHeight: 88,
    borderRadius: 22,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  previewVideo: {
    width: 96,
    height: 64,
    borderRadius: radius.md,
    backgroundColor: '#000',
  },
  previewVideoMeta: {
    flex: 1,
    minWidth: 0,
    paddingRight: 30,
  },
  previewVideoTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  previewVideoSubtitle: {
    marginTop: 3,
    fontSize: 12,
  },
  previewRemove: {
    position: 'absolute',
    right: 4,
    top: 4,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.danger,
  },
  previewRemoveText: {
    color: colors.white,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '800',
  },
  pinnedBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 14,
    marginTop: 8,
    marginBottom: 6,
    borderRadius: 22,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    zIndex: 2,
  },
  pinnedStripe: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  pinnedInfo: {
    flex: 1,
    minWidth: 0,
  },
  pinnedTitle: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  pinnedText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
  },
  pinnedHint: {
    color: colors.soft,
    fontSize: 11,
    lineHeight: 14,
  },
  sendStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  sendStatusText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  replyBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOpacity: colors.isDark ? 0.06 : 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: colors.isDark ? 1 : 2,
  },
  replyInfo: {
    flex: 1,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    paddingLeft: 10,
  },
  replyTitle: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  replyText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  editingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOpacity: colors.isDark ? 0.06 : 0.1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: colors.isDark ? 1 : 2,
  },
  editingInfo: {
    flex: 1,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
    paddingLeft: 10,
  },
  editingTitle: {
    color: colors.accent,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  editingText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  editingCancel: {
    width: 34,
    height: 34,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  editingCancelText: {
    color: colors.muted,
    fontSize: 24,
    lineHeight: 26,
    fontWeight: '600',
  },
  recordingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surfaceMuted,
  },
  recordingDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.danger,
  },
  recordingTime: {
    minWidth: 38,
    color: colors.accentStrong,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
  recordingText: {
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  recordingCancel: {
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
  },
  recordingCancelText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  recordingSend: {
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.accent,
  },
  recordingSendText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  previewVideoNoteCard: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    padding: spacing.sm,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  previewVideoNoteMeta: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  previewVideoNoteActions: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingLeft: 0,
    paddingTop: 0,
    gap: spacing.sm,
  },
  previewHint: {
    color: colors.soft,
    fontSize: 12,
    lineHeight: 16,
  },
  // Preview voice card (new UX: record -> preview -> send/delete)
  previewVoiceCard: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    padding: spacing.sm,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
    gap: 8,
  },
  previewVoiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  previewPlayButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewPlayButtonActive: {
    backgroundColor: colors.accentStrong,
  },
  previewProgressBar: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  previewProgressFill: {
    height: '100%',
    backgroundColor: colors.accent,
  },
  previewDuration: {
    minWidth: 72,
    textAlign: 'right',
    fontSize: 11,
    fontVariant: ['tabular-nums'],
    color: colors.muted,
  },
  previewMeta: {
    paddingLeft: 42,
  },
  previewMetaText: {
    fontSize: 10,
    color: colors.muted,
  },
  previewActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.sm,
    paddingLeft: 42,
    paddingTop: 4,
  },
  typingBar: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  typingText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  composerDock: {
    flexShrink: 0,
    borderTopWidth: 0,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 6,
    backgroundColor: 'transparent',
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 5,
    minHeight: 56,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 28,
    paddingHorizontal: 6,
    paddingVertical: 5,
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOpacity: colors.isDark ? 0.1 : 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: colors.isDark ? 2 : 5,
  },
  composerSideButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 0,
    marginBottom: 2,
    backgroundColor: colors.cardMuted,
  },
  composerInputContainer: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'flex-end',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 22,
    paddingLeft: 12,
    paddingRight: 2,
    backgroundColor: colors.input,
  },
  composerEmojiButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
  },
  composerButtonPressed: {
    opacity: 0.72,
  },
  composerButtonDisabled: {
    opacity: 0.42,
  },
  composerActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginBottom: 1,
  },
  composerActionRecording: {
    backgroundColor: colors.danger,
    borderColor: colors.danger,
    opacity: 1,
  },
  input: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 7,
    color: colors.text,
    fontSize: 16,
    lineHeight: 21,
  },
  lightbox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    padding: 14,
  },
  lightboxBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  lightboxImage: {
    width: '100%',
    height: '86%',
  },
  lightboxVideo: {
    width: '100%',
    height: '86%',
  },
  lightboxClose: {
    position: 'absolute',
    right: 18,
    top: 18,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  lightboxCloseText: {
    color: colors.white,
    fontSize: 30,
    lineHeight: 32,
    fontWeight: '600',
  },
  sheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(8, 19, 31, 0.48)',
  },
  sheet: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 6,
    shadowColor: colors.shadow,
    shadowOpacity: colors.isDark ? 0 : 0.18,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: -12 },
    elevation: colors.isDark ? 0 : 8,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.border,
    marginBottom: 8,
  },
  sheetTitle: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    paddingHorizontal: 6,
    paddingBottom: 4,
    textTransform: 'uppercase',
  },
  sheetAction: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.cardMuted,
  },
  sheetActionIcon: {
    width: 34,
    height: 34,
    borderRadius: radius.pill,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  sheetActionText: {
    color: colors.text,
    ...typography.body,
    fontWeight: '600',
  },
  forwardPreview: {
    borderRadius: radius.lg,
    padding: spacing.md,
    backgroundColor: colors.surfaceMuted,
    marginBottom: 6,
  },
  forwardPreviewText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 19,
  },
  forwardError: {
    color: colors.danger,
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 6,
  },
  forwardLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
  },
  forwardEmpty: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    padding: 12,
  },
  forwardList: {
    maxHeight: 320,
    gap: 6,
  },
  forwardRecipient: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    backgroundColor: colors.surfaceMuted,
  },
  forwardRecipientSelected: {
    borderColor: colors.accent,
  },
  forwardRecipientName: {
    flex: 1,
    color: colors.text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
  forwardCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    color: colors.muted,
    backgroundColor: colors.surface,
    fontSize: 17,
    lineHeight: 28,
    textAlign: 'center',
    fontWeight: '900',
  },
  forwardCheckSelected: {
    color: colors.white,
    backgroundColor: colors.accent,
  },
  forwardActions: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 10,
  },
  forwardButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  forwardCancelButton: {
    backgroundColor: colors.surfaceMuted,
  },
  forwardSubmitButton: {
    backgroundColor: colors.accent,
  },
  forwardCancelText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  forwardSubmitText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
  },
  sheetDangerAction: {
    marginTop: 2,
  },
  sheetDangerIcon: {
    backgroundColor: colors.dangerSoft,
    color: colors.danger,
  },
  sheetDangerText: {
    color: colors.danger,
  },
});
